staging-settings:
  user-workflow:
    workflow-name: "generator-workflow"
  workflow-artifacts:
    workflow-path: "./workflow.ts"
    config-path: "./config.json"
    secrets-path: "./secrets.yaml"
